In [5]:
import numpy as np
import random
#import itertools
import scipy.misc

import matplotlib
#matplotlib.use('qt5agg')
import matplotlib.pyplot as plt

#%matplotlib notebook
%matplotlib qt 
#%matplotlib inline 
import time

# gridworldclass that we made
from gridworldclass import gameEnv
from Agents import SRTD_agent, TDagent



In [2]:
# TD learning agent

plt.close("all")
# how many plots to make during episode? - here we'll make 2
f,(ax1, ax2) = plt.subplots(2)

# build environment

# build wall - wall x has x cordinate of wall, y has y coordinates
wall_x = np.array([2,2,2,2,3,4,5,6,6,6,6])
wall_y = np.array([5,4,3,2,2,2,2,2,3,4,5])
wall_loc = np.array([wall_y, wall_x]).T

nrows = 10 # number of rows in grid (0-n-1)
ncols = 10 # number of cols in grid (0-n-1)
reward_loc = np.array([[4,4]]) # reward location - give one row for each reward
reward_mag = np.array([2]) # reward mag - give one value for each reward
start_pos = np.array([1,2]) # starting position of agent on each episode
env = gameEnv(nrows,ncols,reward_loc, reward_mag,wall_loc, start_pos)

# make agent
params = {'alpha': .5, 'gamma': .5, 'lam': .5, 'epsilon': .9}
ag = TDagent(params,env.nrows,env.ncols)

# run game
nepisodes = 100
max_step = 100

for i in range(nepisodes):

    # repeat for each episode
    d = False
    j = 0
    S = env.reset()
    ag.set_S(S)

    while j < max_step:
        # draw environment and pause
        env.render(ax1)
        ag.render_V(ax2)

        plt.pause(.05)
        # increase counter
        j += 1
        
        # get next state for each action (probably want to pre-compute this)
        next_states = np.zeros(4);
        for c in range(4):
            (next_states[c],_,_) = env.lookahead(S,c)
        
        # agent gets to see next possible states
        ag.set_next_states(next_states)
        
        # sample action given by pi for state S
        a = ag.sample_action()
        
        # take action A, observe s1, r, terminal?
        S_prime,r,d = env.step(a)
        ag.set_S_prime(S_prime)
        ag.set_r(r)

        # update model
        ag.update()
        
        # update S
        S = S_prime;
        ag.set_S(S)
    
        if d == True:
            break
            



/Users/evanrussek/anaconda/lib/python3.5/site-packages/matplotlib/backend_bases.py:2437: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


KeyboardInterrupt: 

In [ ]:
# SR-TD agent

plt.close("all")
show = 1 # make plots?

if show == 1:
    f,(ax1, ax2, ax3) = plt.subplots(3)

# build wall
wall_x = np.array([]);
wall_y = np.array([]);
wall_loc = np.array([wall_y, wall_x]).T
wall_states = np.zeros(wall_loc.shape[0])

#gameEnv(nrows,ncols,reward_loc, reward_mag,wall_loc, start_pos)
nrows = 4
ncols = 10
reward_loc = np.array([[0,0]])
reward_mag = np.array([1])
start_pos = np.array([0,9])
env = gameEnv(nrows,ncols,reward_loc, reward_mag,wall_loc, start_pos)

params = {'alpha_sr': .1, 'alpha_w': .5, 'gamma': .9, 'lam': .5, 'epsilon': .1}

ag = SRTD_agent(params,env.nrows,env.ncols)

nepisodes = 10
max_step = 100

for i in range(nepisodes):

    # repeat for each episode
    d = False
    j = 0
    S = env.reset()
    ag.set_S(S)

    while j < max_step:
        if show == 1:
            # draw environment and pause
            env.render(ax1)
            ag.render_V(ax2)
            ag.render_M(ax3)
            plt.pause(.02)
            
        # increase counter
        j += 1
        
        # get next state for each action (probably want to pre-compute this)
        next_states = np.zeros(4);
        for c in range(4):
            (next_states[c],_,_) = env.lookahead(S,c)
        
        # agent gets to see next possible states
        ag.set_next_states(next_states)
        
        # sample action given by pi for state S
        a = ag.sample_action()
        
        # take action A, observe s1, r, terminal?
        S_prime,r,d = env.step(a)
        ag.set_S_prime(S_prime)
        ag.set_r(r)

        # update model
        ag.update()
        
        # update S
        S = S_prime;
        
        ag.set_S(S)
    
        if d == True:
            break
            



In [2]:
np.log(1)

NameError: name 'np' is not defined

In [4]:
env.lookaheadmtx

array([[  0.,  10.,   0.,   1.],
       [  1.,  11.,   0.,   2.],
       [  2.,  12.,   1.,   3.],
       [  3.,  13.,   2.,   4.],
       [  4.,  14.,   3.,   5.],
       [  5.,  15.,   4.,   6.],
       [  6.,  16.,   5.,   7.],
       [  7.,  17.,   6.,   8.],
       [  8.,  18.,   7.,   9.],
       [  9.,  19.,   8.,   9.],
       [  0.,  20.,  10.,  11.],
       [  1.,  21.,  10.,  12.],
       [  2.,  12.,  11.,  13.],
       [  3.,  13.,  12.,  14.],
       [  4.,  14.,  13.,  15.],
       [  5.,  15.,  14.,  16.],
       [  6.,  16.,  15.,  17.],
       [  7.,  27.,  16.,  18.],
       [  8.,  28.,  17.,  19.],
       [  9.,  29.,  18.,  19.],
       [ 10.,  30.,  20.,  21.],
       [ 11.,  31.,  20.,  21.],
       [ 12.,  22.,  21.,  22.],
       [ 13.,  33.,  23.,  23.],
       [ 14.,  34.,  24.,  24.],
       [ 15.,  35.,  25.,  25.],
       [ 16.,  26.,  26.,  27.],
       [ 17.,  37.,  27.,  28.],
       [ 18.,  38.,  27.,  29.],
       [ 19.,  39.,  28.,  29.],
       [ 2

In [23]:
nstates = env.nrows*env.ncols
pol_mtx = .25*np.ones([nstates,4])
T_ss = np.zeros([nstates,nstates])
for s in np.arange(nstates):
    for i in np.arange(4):
        s_prime = int(env.lookaheadmtx[s,i])
        T_ss[s,s_prime] = pol_mtx[s,i]
    

In [32]:
T_sas = np.zeros([nstates,4,nstates])
for s in np.arange(nstates):
    for a in np.arange(4):
        s_prime = int(env.lookaheadmtx[s,a])
        T_sas[s,a,s_prime] = 1


In [31]:
T_sas[1,1,:]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [2]:
# build wall - wall x has x cordinate of wall, y has y coordinates
wall_x = np.array([2,2,2,2,3,4,5,6,6,6,6])
wall_y = np.array([5,4,3,2,2,2,2,2,3,4,5])
wall_loc = np.array([wall_y, wall_x]).T

nrows = 10 # number of rows in grid (0-n-1)
ncols = 10 # number of cols in grid (0-n-1)
reward_loc = np.array([[4,4]]) # reward location - give one row for each reward
reward_mag = np.array([2]) # reward mag - give one value for each reward
start_pos = np.array([1,2]) # starting position of agent on each episode
env = gameEnv(nrows,ncols,reward_loc, reward_mag,wall_loc, start_pos)


In [3]:
Tsas = env.make_Tsas()

array([[[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ..., 
       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.